









































});  console.log(`Server running in ${process.env.NODE_ENV} mode on port ${PORT}`);httpServer.listen(PORT, () => {setupVoiceChatHandlers(io);});  },    credentials: true,    methods: ['GET', 'POST'],    origin: process.env.FRONT_END_URL,  cors: {const io = new Server(httpServer, {const PORT = process.env.PORT || 5000;app.use(errorHandler);app.use(notFound);app.use('/api/voice', voiceChatRoutes);app.use('/api/openai', openaiRoutes);app.use('/api/users', userRoutes);app.use(express.json());const httpServer = createServer(app);const app = express();connectDB();dotenv.config();import setupVoiceChatHandlers from './socket/voiceChatHandler.js';import voiceChatRoutes from './routes/voiceChatRoutes.js';import openaiRoutes from './routes/openaiRoutes.js';import userRoutes from './routes/userRoutes.js';import { notFound, errorHandler } from './middleware/errorMiddleware.js';import connectDB from './config/db.js';import { Server } from 'socket.io';import { createServer } from 'http';import dotenv from 'dotenv';import express from 'express';